### ISSUE TITLE
Use another sep char between selection_id and runner_name

### ISSUE THREAD

**Issue by nachouve** [nachouve/betfairviz#1]
In SCORE_CORRECT market the visualization  `selection_id + " - " + runner_name`  is a bit confusing:

> 1 - 0 - 0
> 4 - 0 - 1
> 9 - 0 - 2
> 16 - 0 - 3
> 2 - 1 - 0
> 3 - 1 - 1
> 8  - 1 - 2
> 15 - 1 - 3

I suggest using " | " as separator.

**Comment by nachouve** [comment]
Now it's shown as:

> 1 | 0 - 0	
> 4 | 0 - 1	
> 9 | 0 - 2	
> 16 | 0 - 3	
> 2 | 1 - 0	
> 3 | 1 - 1
> 8 | 1 - 2
	
![new_sep_runner_names](https://user-images.githubusercontent.com/874798/163174865-9ca707b4-cdbc-4a14-acfe-81aca9bca6df.png)

**Comment by nachouve** [comment]
@mberk Do you like this small change?

**Comment by mberk** [comment]
Yes this is a very good idea but I would parametrise the separator in case people like the current one

**Comment by nachouve** [comment]
Ok.

Also, can it be parametrized the currency symbol? And the "GBP" at `<span class="total-matched">GBP {total_matched}>` ?

**Comment by mberk** [comment]
Yes definitely

**Comment by mberk** [comment]
> Ok.
> 
> Also, can it be parametrized the currency symbol? And the "GBP" at `<span class="total-matched">GBP {total_matched}>` ?

See https://github.com/mberk/betfairviz/tree/issue-23 - e.g. `create_dashboard(..., currency="EUR")`
