### ISSUE TITLE
Change color of negative values in market_book_diff_table

### ISSUE THREAD

**Issue by nachouve** [nachouve/betfairviz#2]
I think can be useful add color to the market_book differences depending if the size is greater or lower.

**Comment by nachouve** [comment]
@mberk Do you like this small change?

**Comment by mberk** [comment]
Do you have a screenshot?

**Comment by nachouve** [comment]
Sure!

![negative_sizes](https://user-images.githubusercontent.com/874798/163173794-827e4cda-ca44-4aed-84a9-913cf5bf3deb.png)

This way, I think it is easy to follow the movement of sizes.

**Comment by mberk** [comment]
Yeah I think it looks very nice. Personally I would make some minor changes to the CSS (call it .negative instead of .is_negative - there is a precedent of using .negative in the original CSS; also have a space between .bet-button-size and .negative)

**Comment by nachouve** [comment]
Do I change that and send a pull request? Or how? 
Whatever you prefer, for that tiny thing...

**Comment by mberk** [comment]
If you create a PR I can merge and then make the tweaks

**Comment by nachouve** [comment]
Ok.
Humm... if I remove the space  between `.bet-button-size.negative` do not apply the style.
